version: '3.8'

services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: Pass!w0rd
      POSTGRES_DB: assignment
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  airflow-webserver:
    image: apache/airflow:2.10.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:Pass!w0rd@db:5432/assignment
      AIRFLOW__CORE__FERNET_KEY: BBVT3jrzY-ssk_KaR5FWsuYfpeAbprCq79Ej9HEpjVQ=
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    networks:
      - my_network
    depends_on:
      - db
    command: ["webserver"]  # Explicit command for webserver service

  airflow-scheduler:
    image: apache/airflow:2.10.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:Pass!w0rd@db:5432/assignment
      AIRFLOW__CORE__FERNET_KEY: BBVT3jrzY-ssk_KaR5FWsuYfpeAbprCq79Ej9HEpjVQ=
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    networks:
      - my_network
    depends_on:
      - db
    command: ["scheduler"]  # Explicit command for scheduler service

networks:
  my_network:
    driver: bridge
