version: '3.8'

services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: Pass!w0rd
      POSTGRES_DB: assignment
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "data_engineer"]
      interval: 10s
      retries: 5

  airflow-init:
    image: apache/airflow:2.6.3
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:Pass!w0rd@db:5432/assignment
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow.db:/usr/local/airflow/airflow.db
    depends_on:
      db:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:2.10.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:Pass!w0rd@db:5432/assignment
      AIRFLOW__CORE__FERNET_KEY: BBVT3jrzY-ssk_KaR5FWsuYfpeAbprCq79Ej9HEpjVQ=
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    networks:
      - my_network
    depends_on:
      - db
    command: ["webserver"]  # Explicit command for webserver service

  airflow-scheduler:
    image: apache/airflow:2.10.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:Pass!w0rd@db:5432/assignment
      AIRFLOW__CORE__FERNET_KEY: BBVT3jrzY-ssk_KaR5FWsuYfpeAbprCq79Ej9HEpjVQ=
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    networks:
      - my_network
    depends_on:
      - db
    command: ["scheduler"]  # Explicit command for scheduler service

networks:
  my_network:
    driver: bridge
