version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:2.6.1
    depends_on:
      - db
    entrypoint: /bin/bash
    command: ["-c", "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"]
    volumes:
      - ./airflow/scripts:/scripts
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
      - ./airflow/logs:/opt/airflow/logs
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.6.1
    depends_on:
      - airflow-init
      - db
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
      - ./airflow/logs:/opt/airflow/logs
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.6.1
    depends_on:
      - airflow-init
      - db
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
      - ./airflow/logs:/opt/airflow/logs
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
