services:
  streamlit_app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - ../airflow/data:/airflow/data
      #- ./airflow/data:/airflow/data
      - ./app:/app
      - ./logs:/app/logs
    environment:
      STREAMLIT_SERVER_PORT: 8501
    working_dir: /app